### ISSUE TITLE
Minor typo in Stable Diffusion Deep Dive notebook

### ISSUE THREAD

**Issue by daspartho** [fastai/diffusion-nbs#9]
Hi, @johnowhitaker 

In the positional embedding section at the line
> But now instead of dealing with ~50 tokens we just need one for each position (77 total):

I think the number of tokens should be 50K instead of 50. Could you please confirm this?

Thanks

**Comment by johnowhitaker** [comment]
You're right that should be 50K - I'll change that along with one or two other tweaks soon.Thanks :)
